import type { TripState } from './types'

export function createSeedTripState(): TripState {
  const now = new Date().toISOString()

  return {
    travelers: [
      { id: 'traveler-a', name: 'Матвей', color: '#e11d48', sortOrder: 1 },
      { id: 'traveler-b', name: 'Артур', color: '#0891b2', sortOrder: 2 },
      { id: 'traveler-c', name: 'Лера', color: '#ca8a04', sortOrder: 3 },
    ],
    placeSections: [
      { id: 'sight', title: 'Достопримечательности', sortOrder: 10 },
      { id: 'food', title: 'Еда', sortOrder: 20 },
      { id: 'shopping', title: 'Шопинг', sortOrder: 30 },
    ],
    days: [
      {
        id: 'day-aug-08-road',
        date: '2026-08-08',
        city: 'Дорога',
        note: 'Старт поездки. Проверить паспорта, билеты, eSIM/VPN и ночной перелёт.',
      },
      {
        id: 'day-aug-09-guangzhou',
        date: '2026-08-09',
        city: 'Гуанчжоу',
        note: 'Прилёт, заселение, спокойная прогулка и адаптация.',
      },
      {
        id: 'day-aug-10-guangzhou',
        date: '2026-08-10',
        city: 'Гуанчжоу',
        note: 'Первый полный день в городе.',
      },
      {
        id: 'day-aug-11-guangzhou',
        date: '2026-08-11',
        city: 'Гуанчжоу',
        note: 'Последний полный день перед переездом в Яншо.',
      },
      {
        id: 'day-aug-12-yangshuo',
        date: '2026-08-12',
        city: 'Яншо',
        note: 'Переезд Гуанчжоу → Яншо, заселение и вечерняя прогулка.',
      },
      {
        id: 'day-aug-13-yangshuo',
        date: '2026-08-13',
        city: 'Яншо',
        note: 'Горы, река Ли/Юйлун и красивый неторопливый день.',
      },
      {
        id: 'day-aug-14-guangzhou',
        date: '2026-08-14',
        city: 'Гуанчжоу',
        note: 'Возвращение из Яншо в Гуанчжоу.',
      },
      {
        id: 'day-aug-15-guangzhou',
        date: '2026-08-15',
        city: 'Гуанчжоу',
        note: 'Свободный день в Гуанчжоу.',
      },
      {
        id: 'day-aug-16-shanghai-option',
        date: '2026-08-16',
        city: 'Гуанчжоу / Шанхай',
        note: 'Опционально: один день в Шанхае, если удобно по билетам и силам.',
      },
      {
        id: 'day-aug-17-guangzhou',
        date: '2026-08-17',
        city: 'Гуанчжоу',
        note: 'Запасной день для мест, еды и покупок.',
      },
      {
        id: 'day-aug-18-guangzhou',
        date: '2026-08-18',
        city: 'Гуанчжоу',
        note: 'Запасной день в городе.',
      },
      {
        id: 'day-aug-19-guangzhou',
        date: '2026-08-19',
        city: 'Гуанчжоу',
        note: 'Финальные дела перед вылетом домой.',
      },
      {
        id: 'day-aug-20-road',
        date: '2026-08-20',
        city: 'Дорога домой',
        note: 'Окончание поездки.',
      },
    ],
    places: [
      {
        id: 'place-canton-tower',
        name: 'Canton Tower',
        city: 'Гуанчжоу',
        category: 'sight',
        url: 'https://maps.apple.com/?q=Canton%20Tower%20Guangzhou',
        note: 'Хорошо оставить на вечер: вид на город и набережную.',
        photoUrl:
          'https://images.unsplash.com/photo-1579683670728-96c9abc569b1?auto=format&fit=crop&w=900&q=80',
        status: 'want',
        dayId: 'day-aug-09-guangzhou',
        createdAt: now,
      },
      {
        id: 'place-shamian',
        name: 'Shamian Island',
        city: 'Гуанчжоу',
        category: 'sight',
        url: 'https://maps.apple.com/?q=Shamian%20Island%20Guangzhou',
        note: 'Прогулка, кофе, колониальная архитектура.',
        photoUrl:
          'https://images.unsplash.com/photo-1599571234909-29ed5d1321d6?auto=format&fit=crop&w=900&q=80',
        status: 'want',
        dayId: 'day-aug-10-guangzhou',
        createdAt: now,
      },
      {
        id: 'place-yulong-river',
        name: 'Yulong River',
        city: 'Яншо',
        category: 'sight',
        url: 'https://maps.apple.com/?q=Yulong%20River%20Yangshuo',
        note: 'Главная точка для Яншо: река, карстовые горы, вело/рафтинг.',
        photoUrl:
          'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?auto=format&fit=crop&w=900&q=80',
        status: 'want',
        dayId: 'day-aug-13-yangshuo',
        createdAt: now,
      },
      {
        id: 'place-shanghai-option',
        name: 'Шанхай на один день',
        city: 'Шанхай',
        category: 'sight',
        url: 'https://maps.apple.com/?q=Shanghai',
        note: 'Опциональный день: решим после понимания билетов и темпа поездки.',
        photoUrl:
          'https://images.unsplash.com/photo-1548919973-5cef591cdbc9?auto=format&fit=crop&w=900&q=80',
        status: 'want',
        dayId: 'day-aug-16-shanghai-option',
        createdAt: now,
      },
    ],
    hotels: [
      {
        id: 'hotel-guangzhou-first',
        name: 'Отель в Гуанчжоу',
        city: 'Гуанчжоу',
        address: '',
        checkIn: '2026-08-09',
        checkOut: '2026-08-12',
        price: 0,
        currency: 'CNY',
        url: '',
        confirmationUrl: '',
        note: 'Первая база: 9-12 августа.',
      },
      {
        id: 'hotel-yangshuo',
        name: 'Отель в Яншо',
        city: 'Яншо',
        address: '',
        checkIn: '2026-08-12',
        checkOut: '2026-08-14',
        price: 0,
        currency: 'CNY',
        url: '',
        confirmationUrl: '',
        note: 'Нужен вариант рядом с красивыми маршрутами/рекой.',
      },
      {
        id: 'hotel-guangzhou-final',
        name: 'Отель в Гуанчжоу',
        city: 'Гуанчжоу',
        address: '',
        checkIn: '2026-08-14',
        checkOut: '2026-08-20',
        price: 0,
        currency: 'CNY',
        url: '',
        confirmationUrl: '',
        note: 'Финальная база. Возможен один день в Шанхае.',
      },
    ],
    tickets: [
      {
        id: 'ticket-flight-guangzhou',
        kind: 'flight',
        fromCity: 'Дом',
        toCity: 'Гуанчжоу',
        departAt: '2026-08-08T20:00',
        arriveAt: '2026-08-09T12:00',
        refNumber: '',
        seat: '',
        price: 0,
        currency: 'CNY',
        url: '',
        fileUrl: '',
      },
      {
        id: 'ticket-guangzhou-yangshuo',
        kind: 'train',
        fromCity: 'Гуанчжоу',
        toCity: 'Яншо',
        departAt: '2026-08-12T10:00',
        arriveAt: '2026-08-12T13:00',
        refNumber: '',
        seat: '',
        price: 0,
        currency: 'CNY',
        url: '',
        fileUrl: '',
      },
      {
        id: 'ticket-yangshuo-guangzhou',
        kind: 'train',
        fromCity: 'Яншо',
        toCity: 'Гуанчжоу',
        departAt: '2026-08-14T12:00',
        arriveAt: '2026-08-14T15:00',
        refNumber: '',
        seat: '',
        price: 0,
        currency: 'CNY',
        url: '',
        fileUrl: '',
      },
    ],
    dayItems: [
      {
        id: 'item-flight-guangzhou',
        dayId: 'day-aug-08-road',
        kind: 'ticket',
        refId: 'ticket-flight-guangzhou',
        sortOrder: 10,
      },
      {
        id: 'item-hotel-guangzhou-first',
        dayId: 'day-aug-09-guangzhou',
        kind: 'hotel',
        refId: 'hotel-guangzhou-first',
        sortOrder: 10,
      },
      {
        id: 'item-canton-tower',
        dayId: 'day-aug-09-guangzhou',
        kind: 'place',
        refId: 'place-canton-tower',
        sortOrder: 20,
      },
      {
        id: 'item-shamian',
        dayId: 'day-aug-10-guangzhou',
        kind: 'place',
        refId: 'place-shamian',
        sortOrder: 10,
      },
      {
        id: 'item-guangzhou-yangshuo',
        dayId: 'day-aug-12-yangshuo',
        kind: 'ticket',
        refId: 'ticket-guangzhou-yangshuo',
        sortOrder: 10,
      },
      {
        id: 'item-hotel-yangshuo',
        dayId: 'day-aug-12-yangshuo',
        kind: 'hotel',
        refId: 'hotel-yangshuo',
        sortOrder: 20,
      },
      {
        id: 'item-yulong-river',
        dayId: 'day-aug-13-yangshuo',
        kind: 'place',
        refId: 'place-yulong-river',
        sortOrder: 10,
      },
      {
        id: 'item-yangshuo-guangzhou',
        dayId: 'day-aug-14-guangzhou',
        kind: 'ticket',
        refId: 'ticket-yangshuo-guangzhou',
        sortOrder: 10,
      },
      {
        id: 'item-hotel-guangzhou-final',
        dayId: 'day-aug-14-guangzhou',
        kind: 'hotel',
        refId: 'hotel-guangzhou-final',
        sortOrder: 20,
      },
      {
        id: 'item-shanghai-option',
        dayId: 'day-aug-16-shanghai-option',
        kind: 'place',
        refId: 'place-shanghai-option',
        sortOrder: 10,
      },
    ],
    expenses: [],
    expenseShares: [],
    expenseSplits: [],
    payments: [],
    checklists: [
      { id: 'check-visa', title: 'Визы и документы', kind: 'visa' },
      { id: 'check-packing', title: 'Что взять', kind: 'packing' },
      { id: 'check-phrases', title: 'Полезные фразы', kind: 'phrases' },
    ],
    checklistItems: [
      {
        id: 'item-passport',
        checklistId: 'check-visa',
        text: 'Паспорта действуют 6+ месяцев после поездки',
        done: false,
        sortOrder: 10,
      },
      {
        id: 'item-insurance',
        checklistId: 'check-visa',
        text: 'Страховка и скрины виз/броней сохранены офлайн',
        done: false,
        sortOrder: 20,
      },
      {
        id: 'item-vpn',
        checklistId: 'check-packing',
        text: 'VPN, eSIM, карты, офлайн-переводчик',
        done: false,
        sortOrder: 10,
      },
      {
        id: 'item-nihao',
        checklistId: 'check-phrases',
        text: '你好 - здравствуйте',
        done: false,
        sortOrder: 10,
      },
      {
        id: 'item-xiexie',
        checklistId: 'check-phrases',
        text: '谢谢 · Xiè xie — спасибо',
        done: false,
        sortOrder: 20,
      },
      {
        id: 'item-buyaola',
        checklistId: 'check-phrases',
        text: '不要辣 · Bù yào là — не остро, пожалуйста',
        done: false,
        sortOrder: 30,
      },
    ],
    settings: {
      cnyToRubRate: 11.4,
      rateUpdatedAt: now,
      displayCurrency: 'CNY',
      theme: 'system',
    },
  }
}
